- arguments: [--cpp-define=HLINT, --cpp-ansi]

- ignore: {name: Use section}
- ignore: {name: Redundant lambda}
- ignore: {name: Use const}
- ignore: {name: Avoid lambda}
- ignore: {name: Avoid lambda using `infix`}
- ignore: {name: Use sequenceA, within: [Data.Distributive.Internal]} 
